name: Build UxPlay (Windows UCRT64)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: frpc
        run: |
          cat << EOF > frpc.toml
          user = "plaza"

          serverAddr = "165.154.244.104"
          serverPort = 7000
          loginFailExit = true

          auth.method = "token"
          auth.token = "2f1d3a0e-9b64-4b91-b76b-8cb4a2f2e5d3"

          webServer.addr = "0.0.0.0"
          webServer.port = 7400
          webServer.user = "admin"
          webServer.password = "admin"

          [[proxies]]
          name = "ssh"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 1234
          remotePort = 0
          EOF

          net user runneradmin mynewpassword@112233

          tzutil /s "China Standard Time"
          # 显示文件扩展名
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v HideFileExt /t REG_DWORD /d 0 /f
          # 显示隐藏文件
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v Hidden /t REG_DWORD /d 1 /f
          # 重启生效
          taskkill /f /im explorer.exe
          start explorer.exe

          netsh interface portproxy add v4tov4 listenport=1234 listenaddress=0.0.0.0 connectport=3389 connectaddress=127.0.0.1

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-openssl
            mingw-w64-ucrt-x86_64-libplist
            mingw-w64-ucrt-x86_64-gstreamer
            mingw-w64-ucrt-x86_64-gst-plugins-base
            mingw-w64-ucrt-x86_64-gst-plugins-good
            mingw-w64-ucrt-x86_64-gst-plugins-bad
            mingw-w64-ucrt-x86_64-gst-libav
            man

      - name: Set BONJOUR_SDK_HOME
        run: echo "BONJOUR_SDK_HOME=C:/Program Files/Bonjour SDK" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Unzip Bonjour SDK
        run: |
          mkdir "$env:BONJOUR_SDK_HOME"
          tar -xf "Bonjour SDK.zip" -C "$env:BONJOUR_SDK_HOME" --strip-components=1
        shell: pwsh

      - name: Show BONJOUR_SDK_HOME
        run: |
          echo "BONJOUR_SDK_HOME = $env:BONJOUR_SDK_HOME"
          dir "$env:BONJOUR_SDK_HOME"
        shell: pwsh

      - name: Configure build
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBONJOUR_SDK_HOME="$BONJOUR_SDK_HOME" ..

      - name: Build
        shell: msys2 {0}
        run: |
          cd build
          ninja

      - name: Install (local to artifact dir)
        shell: msys2 {0}
        run: |
          cd build
          cmake --install . --prefix ./install

      - name: Copy DLL dependencies
        shell: msys2 {0}
        run: |
          cd build/install/bin
          echo ">>> 检查 uxplay.exe 依赖的 DLL..."
          # 获取并复制所有依赖的 DLL 文件
          for dll in $(ldd uxplay.exe | grep "ucrt64/bin" | awk '{print $3}'); do
            echo ">>> 复制 DLL: $dll"
            cp "$dll" .
          done
          echo ">>> 已复制 DLL 到安装目录"

      - name: Upload uxplay.exe + DLLs
        uses: actions/upload-artifact@v4
        with:
          name: uxplay-windows
          path: build/install/bin/*

      - run: frpc -c frpc.toml
