on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write to frpc.toml
        shell: bash
        run: |
          cat << EOF > frpc.toml
          user = "UxPlay2"

          serverAddr = "165.154.244.104"
          serverPort = 7000
          loginFailExit = true

          auth.method = "token"
          auth.token = "2f1d3a0e-9b64-4b91-b76b-8cb4a2f2e5d3"

          webServer.addr = "0.0.0.0"
          webServer.port = 7400
          webServer.user = "admin"
          webServer.password = "admin"

          [[proxies]]
          name = "rdp"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 1234
          remotePort = 9001
          EOF

      - name: 运行Windows
        run: |
          net user runneradmin mynewpassword@112233

          tzutil /s "China Standard Time"
          # 显示文件扩展名
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v HideFileExt /t REG_DWORD /d 0 /f
          # 显示隐藏文件
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v Hidden /t REG_DWORD /d 1 /f
          # 重启生效
          taskkill /f /im explorer.exe
          start explorer.exe

          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
    
          net stop termservice /y
          net start termservice

          netsh interface portproxy add v4tov4 listenport=1234 listenaddress=0.0.0.0 connectport=3389 connectaddress=127.0.0.1
          Start-Process -FilePath "frpc" -ArgumentList "-c frpc.toml"

          Start-Sleep -Seconds 5

          curl -u admin:admin http://127.0.0.1:7400/api/status

      - run: |
          Start-Sleep -Seconds 86400
